name: .NET

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build
    - name: Publish
      run: dotnet publish QuizExperiment.Admin/Server/QuizExperiment.Admin.Server.csproj -c Release -o website
    - name: Upload a Build Artifact (Website)
      uses: actions/upload-artifact@v2.2.2
      with:
        name: website
        path: website/**
        if-no-files-found: error
    - name: Upload a Build Artifact (Env)
      uses: actions/upload-artifact@v2.2.2
      with:
        name: env
        path: Env/*.*
        if-no-files-found: error
  deploy:
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    
    env:
      LOCATION: uksouth
      RESOURCEGROUP: quizzr
      APPNAME: quizzr
    
    steps:
    - name: Download a Build Artifact (Website)
      uses: actions/download-artifact@v2.1.0
      with:
        # Artifact name
        name: website
        # Destination path
        path: website
    - name: Download a Build Artifact (Env)
      uses: actions/download-artifact@v2.1.0
      with:
        # Artifact name
        name: env
        # Destination path
        path: Env
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        # Specify the script here
        inlineScript: | 
          az group create -n ${{ env.RESOURCEGROUP }} --location ${{ env.LOCATION }}
          principalId=$(az deployment group create --template-file ./Env/main.bicep -g ${{ env.RESOURCEGROUP }} --parameters giphyApiKey=${{secrets.GIPHYAPIKEY}} --query properties.outputs.webApplicationPrincipalId.value -o tsv)
          # az deployment group create --template-file ./Env/rbac.bicep -g ${{ env.RESOURCEGROUP }} --parameters principalId=$principalId
    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APPNAME }}
        slot-name: production
        package: website

    - name: az cli logout
      run: az logout
    
